config/routes.rb
Rails.application.routes.draw do
  resources :monsters
  root to: 'monsters#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/monster.rb
class Monster < ApplicationRecord
    validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  before_action :set_monster, only: [:show, :edit, :update, :destroy]

  # GET /monsters
  # GET /monsters.json
  def index
    @monsters = Monster.all
  end

  # GET /monsters/1
  # GET /monsters/1.json
  def show
  end

  # GET /monsters/new
  def new
    @monster = Monster.new
  end

  # GET /monsters/1/edit
  def edit
  end

  # POST /monsters
  # POST /monsters.json
  def create
    @monster = Monster.new(monster_params)

    respond_to do |format|
      if @monster.save
        format.html { redirect_to @monster, notice: 'Monster was successfully created.' }
        format.json { render :show, status: :created, location: @monster }
      else
        format.html { render :new }
        format.json { render json: @monster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /monsters/1
  # PATCH/PUT /monsters/1.json
  def update
    respond_to do |format|
      if @monster.update(monster_params)
        format.html { redirect_to @monster, notice: 'Monster was successfully updated.' }
        format.json { render :show, status: :ok, location: @monster }
      else
        format.html { render :edit }
        format.json { render json: @monster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monsters/1
  # DELETE /monsters/1.json
  def destroy
    @monster.destroy
    respond_to do |format|
      format.html { redirect_to monsters_url, notice: 'Monster was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_monster
      @monster = Monster.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def monster_params
      params.require(:monster).permit(:title, :detail, :rarity)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/monsters_helper.rb
module MonstersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mhworld</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <%= render "nav" %>
  <body>
    <%= yield %>
  </body>
<%= render "footer" %>
</html>

app/views/monsters/_footer.html.erb
<footer>
<div class="row">
  <div class="column">
    <h2>Links Group 1</h2>
    <ul>
      <li>
        <a href="#">Monster 1</a>
      </li>
      <li>
        <a href="#">Monster 2</a>
      </li>
      <li>
        <a href="#">Monster 3</a>
      </li>
    </ul>
  </div>
  <div class="column">
    <h2>Links Group 2</h2>
    <ul>
      <li>
        <a href="#">Weapon 1</a>
      </li>
      <li>
        <a href="#">Weapon 2</a>
      </li>
      <li>
        <a href="#">Weapon 3</a>
      </li>
    </ul>
  </div>
</div>
<div class="name">
    © Jerico Radin 2020
</div>
</footer>

app/views/monsters/_form.html.erb
<%= form_with(model: monster, local: true) do |form| %>
  <% if monster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(monster.errors.count, "error") %> prohibited this monster from being saved:</h2>

      <ul>
        <% monster.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :detail %>
    <%= form.text_area :detail %>
  </div>

  <div class="field">
    <%= form.label :rarity %>
    <%= form.number_field :rarity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/monsters/_monster.html.erb
<div class="monster">
    <p>
      <strong>Title:</strong>
      <span class="monsterlink">
        <%= link_to_unless_current monster.title, monster %>
      </span>
    </p>
    
    <p>
      <strong>Detail:</strong>
      <span class="monsterdetail">
        <%= monster.detail %>
      </span>
    </p>
    
    <p>
      <strong>Rarity:</strong>
      <span class="monsterrarity">
        <%= monster.rarity %>
      </span>
    </p>
</div>

app/views/monsters/_nav.html.erb
<nav>
    <a href="#">Home</a> |
    <a href="#">Search</a> |
    <a href="#">Profile</a> |
    <a href="#">Login</a>
</nav>

app/views/monsters/edit.html.erb
<h1>Editing Monster</h1>

<%= render 'form', monster: @monster %>

<%= link_to 'Show', @monster %> |
<%= link_to 'Back', monsters_path %>

app/views/monsters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Monsters</h1>

<%= render @monsters %>

<%= link_to 'New Monster', new_monster_path %>

app/views/monsters/new.html.erb
<h1>New Monster</h1>

<%= render 'form', monster: @monster %>

<%= link_to 'Back', monsters_path %>

app/views/monsters/show.html.erb
<p id="notice"><%= notice %></p>

<%= render @monster %>

<%= link_to 'Edit', edit_monster_path(@monster) %> |
<%= link_to 'Delete', monster_path(@monster), method: :delete, data: {confirm: "Are you sure?"} %> |
<%= link_to 'Back', monsters_path %>